"""comment

Revision ID: 08b3553e3c1d
Revises: f843b6193a1c
Create Date: 2022-05-14 12:40:04.363756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b3553e3c1d'
down_revision = 'f843b6193a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('recipe_steps', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'recipe_steps')
    # ### end Alembic commands ###
