"""comment

Revision ID: 1c49eab89a5e
Revises: 4e413678b6a9
Create Date: 2022-05-11 15:13:37.042110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c49eab89a5e'
down_revision = '4e413678b6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('signature', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('introduction', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'introduction')
    op.drop_column('user', 'signature')
    op.drop_column('user', 'address')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
