"""comment

Revision ID: 2a4984219f2f
Revises: 1c49eab89a5e
Create Date: 2022-05-11 16:45:43.574027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4984219f2f'
down_revision = '1c49eab89a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone', table_name='user')
    op.drop_index('username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'user', ['username'], unique=False)
    op.create_index('phone', 'user', ['phone'], unique=False)
    # ### end Alembic commands ###
