"""comment

Revision ID: 4e413678b6a9
Revises: f2e31281d101
Create Date: 2022-05-11 15:07:20.662033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e413678b6a9'
down_revision = 'f2e31281d101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_phone', sa.String(length=100), nullable=True),
    sa.Column('user_address', sa.String(length=100), nullable=True),
    sa.Column('user_signature', sa.String(length=100), nullable=True),
    sa.Column('user_introduction', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###
