"""comment

Revision ID: 61f04cc0557b
Revises: 419755611b03
Create Date: 2022-05-15 09:59:35.830421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61f04cc0557b'
down_revision = '419755611b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=200), nullable=True))
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
