"""comment

Revision ID: 933719625b28
Revises: 
Create Date: 2022-05-10 17:00:15.760172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933719625b28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('user_email', sa.String(length=200), nullable=False),
    sa.Column('user_password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_setting')
    # ### end Alembic commands ###
