"""comment

Revision ID: f436f31285e8
Revises: 61f04cc0557b
Create Date: 2022-05-15 10:45:05.964801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f436f31285e8'
down_revision = '61f04cc0557b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('avatar', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'avatar')
    # ### end Alembic commands ###
